### ISSUE TITLE
html file does not display as expected

### ISSUE THREAD

**Issue by ivyjansen** [inbo/tutorials#113]
Bij [Les 3 van de "R voor beginners"opleiding](https://inbo.github.io/tutorials/tutorials/r_beginners/) zit er onder de oefening een link naar een [html-pagina](https://github.com/inbo/tutorials/blob/master/content/tutorials/r_beginners/Les3/Scripts/OmtezettenTekst.html). Ik zou die willen laten zien, in plaats van hetgeen nu getoond wordt. De onderliggende .md uploaden zal niet het resultaat geven wat ik wil, want de bedoeling van deze oefening is dat deze html gereproduceerd kan worden vanaf een platte txt, zonder de stijl van de tutorials website. 
Kan iemand mij uitleggen hoe ik dat het beste aanpak?
![image](https://user-images.githubusercontent.com/18716896/55631511-8183ac80-57b8-11e9-9b93-5d5766387c91.png)

**Comment by stijnvanhoey** [comment]
To do so, we should be able to configure 2 elements:
- make sure the `OmtezettenTekst.html` file is also copied to the website pages (currently the file is ignored by settings of hugo)
- change the URL to a HUGO-compliant link, probably something like
`[link-name]({{< relref "/tutorials/r_beginners/Les3/Scripts/OmtezettenTekst.html" >}})`

Unfortunately, I do not yet have a solution for the first element. Anyone else?

**Comment by peterdesmet** [comment]
Note: the html file has been renamed to https://raw.githubusercontent.com/inbo/tutorials/8363ad3873add68772f7dd31b5606da9301ae035/content/tutorials/r_beginners/src/Rmarkdown_oefening_resultaat.html

**Comment by peterdesmet** [comment]
@niconoe, this [html file in `src`](https://raw.githubusercontent.com/inbo/tutorials/8363ad3873add68772f7dd31b5606da9301ae035/content/tutorials/r_beginners/src/Rmarkdown_oefening_resultaat.html) should be pushed _as is_ to the website, but it is currently ignored by Hugo settings. Can you check if an exception can be made for this file?

**Comment by niconoe** [comment]
Will do, thanks!

**Comment by florisvdh** [comment]
Thanks for uptaking this and other issues!

Something which might be related to this issue (and which I'm currently confronted with), is being able to show interactive `leaflet`/`mapview` maps (as well as `ggplotly` maps). Maybe it needs the same approach as this issue. An example is found [here](https://inbo.github.io/tutorials/tutorials/spatial_transform_crs/) at the bottom (and another tutorial is underway).

The pathway of generating `index.md` from `index.Rmd` results in static images instead of embedded JavaScript (the latter is probably needed). If one puts a Pandoc-generated html file inside a tutorial's folder, it is used by Hugo instead of the `index.md` (hence interactive content works) but it misses the website formatting.
