### ISSUE TITLE
This tutorial is great! I made disk.frame to help with large data anlaysis

### ISSUE THREAD

**Issue by xiaodaigh** [inbo/tutorials#147]
https://github.com/xiaoadaigh/disk.frame

I made disk.frame to make it easier to manipulate large data in R, which can complement the materials here:
https://github.com/inbo/tutorials/blob/master/content/tutorials/r_large_data_files_handling/index.Rmd

I have made an issue in the disk.frame repo to contribute to this tutorial at some point https://github.com/xiaodaigh/disk.frame/issues/130

**Comment by peterdesmet** [comment]
Hi @xiaodaigh, sorry for this very late reply. If you are still interested, you are welcome to submit a pull request to mention disk.frame in the [Reading large data files in R](https://inbo.github.io/tutorials/tutorials/r_large_data_files_handling/) tutorial. Since you have a issue open on your end, I am going to close this one here.
