### ISSUE TITLE
tutorial on use of INBO citation style with bibliography managers

### ISSUE THREAD

**Issue by hansvancalster** [inbo/tutorials#168]
Topic: use of INBO citation style with bibliography managers (Zotero, Mendeley, EndNote)

**Comment by hansvancalster** [comment]
Focus of this tutorial should be: how to use the INBO citation style in bibliography managers (Zotero, Mendeley, EndNote)

**Comment by florisvdh** [comment]
Has been updated. Maybe the application to google documents can be used as an example?

**Comment by florisvdh** [comment]
Note, the latest official CSL file of the INBO citation style is the one available at the CSL style repository (also transferred automatically to the Zotero style repository). See https://citationstyles.org/authors/#/finding-and-installing-styles for more information.

Direct links:

- file in the CSL style repository: [.../research-institute-for-nature-and-forest.csl](https://github.com/citation-style-language/styles/blob/master/research-institute-for-nature-and-forest.csl)
- file in the Zotero style repository: https://www.zotero.org/styles/research-institute-for-nature-and-forest

In our forked styles repo, successive (numbered) versions are available: https://github.com/inbo/styles/releases. In that repo also the development branches are kept alive that were merged into the CSL repo, because the latter merges contributing branches as one commit (squash merge).

**Comment by hansvancalster** [comment]
Closed by #212
