### ISSUE TITLE
update r installation instructions for admins

### ISSUE THREAD

**Issue by hansvancalster** [inbo/tutorials#250]
In the documentation of the R and RStudio installation, the installation path of R is changed to `C:\R\R.x.y.z`, while IT still installs R in the `program files` folder.  Today I helped someone encountering problems with it for the second time in two weeks...  No matter which choice is made, but the IT installation and the documentations should correspond. 

And see also #149.

_Originally posted by @ElsLommelen in https://github.com/inbo/tutorials/issues/249#issuecomment-831924856_

**Comment by hansvancalster** [comment]
@ThierryO I think we changed the installation instructions  in July last year back to installing in `C:\R\R.x.y.z` because the space in the `program files` folder gave problems when installing packages such as `rstan` or `brms` that need Rtools tool chain. However, these problems appear to have been solved in the meantime. So I think it is OK that R is installed in the default `program files` folder? Unless there were other reasons why we decided to not follow the default?

**Comment by ElsLommelen** [comment]
Remark: the most important is to change this in the **user** installation instructions, as users only look at this part.  Of course the tutorial looks better if it is changed on both pages, but as IT doesn't use the admin installation instructions as a manual, this has no real impact on the installation process itself.

**Comment by ElsLommelen** [comment]
@hansvancalster Generally the space in the path name causes problems with the rcpp package (which more precisely has to do with c++), so when using packages that depend on this (and certainly when developing rcpp code yourself), the problem can appear.  So this problem is not gone, as far as I know (I can't imagine they will 'fix' this in c++ just for a bunch of R users that use Windows and that want to use c++ to speed up their code), but the chance to encounter this problem is rather low for general INBO users, I think.

Another reason why I suggested to change this, is that it was advised in the instructions of R Core to not use an installation path with a space (which means CRAN packages are not tested if they can deal with this)

**Comment by hansvancalster** [comment]
@ElsLommelen thanks for reminding us. In that case, the current installation instructions in the tutorials can be kept, but still need to be reviewed to check for consistency (in R install for admin, in one place it still refers to `program files`).

**Comment by ElsLommelen** [comment]
@hansvancalster Eh, I'm not sure I understand you correctly.  Why keeping the installation instructions in the tutorials if IT installs R under `program files`?  This is very confusing for users that have to do the user installation after a new update, and certainly for beginning R user that have never done this before (and basically just follow the instructions without knowing what they are doing).  Recently I had 2 questions on it from already more experienced R users: one checked while following these instructions because he couldn't find the installation path on C:\R, and another had just defined the indicated path somehow, which gave some errors at startup.  If even experienced users struggle with this, I think it should certainly be changed to make it correspond with how IT installs R, to make it as clear as possible for beginning R users.

**Comment by hansvancalster** [comment]
Of course, the installation instructions should match how IT installs R. But isn't the conclusion, because of your earlier comment, that IT needs to be informed about the need to install R to C:\R rather than adjusting our installation instructions to match how IT currently installs R?
For me it is also OK to change our installation instructions to match what IT currently does. We just need to decide if what you wrote here https://github.com/inbo/tutorials/issues/250#issuecomment-832078309 is important enough. @ThierryO ?

**Comment by ElsLommelen** [comment]
Another issue is whether it is feasible for IT to change this default. I guess @ThierryO already discussed this with IT.

**Comment by hansvancalster** [comment]
This was issue can be closed because of #255
