### ISSUE TITLE
interactive widgets (e.g. leaflet maps) rendering

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/tutorials#74]
As we decided to use markdown files as the source of the tutorials website, interactive maps are not supported by default (but an image is created instead). Having interactive maps would clarify the functionality.

Options:
* leave as such; when running local, it will work anyway
* adjust and document a workaround by saving the widget as an html-page and load it as e.g. iframe, cfr. https://owi.usgs.gov/blog/leaflet/ ?
* provide special routine within the website building process that overcomes this issue?!?

**Comment by ThierryO** [comment]
is it an option to render those pages directly as html?

**Comment by peterdesmet** [comment]
No, as it won’t pick up the theme. But copy pasting html for the widget itself into the md will work.

**Comment by peterdesmet** [comment]
- Are there interactive maps on other tutorials than https://inbo.github.io/tutorials/tutorials/spatial_create_leaflet_map/ ?
- We could either copy/paste HTML or warn user that the interactive map only work when running the code yourself.

**Comment by florisvdh** [comment]
> Are there interactive maps on other tutorials than https://inbo.github.io/tutorials/tutorials/spatial_create_leaflet_map/ ?

Yes: see example below, and another one in PR #273.

From https://github.com/inbo/tutorials/issues/113#issuecomment-921776011, which probably better suits here: 

> Something which might be related to this issue (and which I'm currently confronted with), is being able to show interactive `leaflet`/`mapview` maps (as well as `ggplotly` maps). Maybe it needs the same approach as this issue. An example is found [here](https://inbo.github.io/tutorials/tutorials/spatial_transform_crs/) at the bottom (and another tutorial is underway).
> 
> The pathway of generating `index.md` from `index.Rmd` results in static images instead of embedded JavaScript (the latter is probably needed). If one puts a Pandoc-generated html file (triggered by the `knitr` package using the Rmd) inside a tutorial's folder, it is used by Hugo instead of the `index.md` (hence interactive content works) but it misses the website formatting.

Your second question:

> We could either copy/paste HTML or warn user that the interactive map only work when running the code yourself.

Probably the second thing is easier to reproduce, e.g. after updating a tutorial.

**Comment by peterdesmet** [comment]
Update on this issue:

There is a way to [include leaflet maps into a page](https://waterdata.usgs.gov/blog/leaflet/), but it requires the libraries `htmlwidgets` and `htmltools`, some hidden code, an iframe and updated theme settings. I didn't manage to get it to work completely and it takes away a lot from the tutorial aspect, i.e. how you would run the code in RStudio. I would therefore not take this approach.

**So I would keep the current option and display the interactive maps as a png, with a note underneath.** Important debug: when knitting the `index.Rmd`, I got the error:
```
Error: Functions that produce HTML output found in document targeting latex output.
Please change the output type of this document to HTML. Alternatively, you can allow
HTML output in non-HTML formats by adding this option to the YAML front-matter of
your rmarkdown file:

  always_allow_html: yes

Note however that the HTML output will not be visible in non-HTML formats.
```
Don't enable `always_allow_html` (as knitting would then generate a html rather than a png). [Rather, do](https://stackoverflow.com/questions/42543206/r-markdown-compile-error):
```R
install.packages("webshot")
webshot::install_phantomjs()
```
Knitting went fine after that.

If we ever want to enable raw html, know that Hugo disables this by default (shows up as `<!-- raw HTML omitted -->` in the rendered site). One can [update the config.toml settings](https://stackoverflow.com/questions/63198652/hugo-shortcode-ignored-saying-raw-html-omitted) to allow this site wide. I have not enable this thus far.

**Comment by florisvdh** [comment]
Thank you Peter for investigating this so well, and for logging the outcome and references here.

It's fine to solve it by adding the note, thanks.

Sidenotes:

- It's a bit strange that you get an error referring to 'latex output' when knitting to `gfm`, maybe that's a bug there.
- Getting this as html code inside `index.md` would indeed need Hugo to copy that.
- Regarding 'it takes away a lot from the tutorial aspect': for the writer, yes (and that may be reason enough), although not for the reader since the author could hide the extra code.

If you'd ever revisit this and get it working, then it seems wise to add it as a tutorial for authors (that use html widgets / leaflet), to be referred by the create-tutorial tutorial :wink:.
